/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.leave;


import com.vacation.manager.jooq.DefaultCatalog;
import com.vacation.manager.jooq.leave.tables.PaidLeave;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Leave extends SchemaImpl {

    private static final long serialVersionUID = 1256782594;

    /**
     * The reference instance of <code>leave</code>
     */
    public static final Leave LEAVE = new Leave();

    /**
     * The table <code>leave.paid_leave</code>.
     */
    public final PaidLeave PAID_LEAVE = PaidLeave.PAID_LEAVE;

    /**
     * No further instances allowed
     */
    private Leave() {
        super("leave", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PAID_LEAVE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            PaidLeave.PAID_LEAVE);
    }
}
