/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.leave;


import com.vacation.manager.jooq.leave.tables.PaidLeave;


/**
 * Convenience access to all tables in leave
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>leave.paid_leave</code>.
     */
    public static final PaidLeave PAID_LEAVE = PaidLeave.PAID_LEAVE;
}
