server:
  port: 9090

app:
  url: "http://localhost:8080"

# Database Properties
spring:
  datasource:
    url: "jdbc:postgresql://localhost:3307/vacation-manager-test"
    username: "postgres"
    password: "klopek1432"
