application:
  admin:
    password: "{bcrypt}$2a$10$N7tHgHhjvt.4AsnW9nMqduLrYLdKFEsP5GKBUPdeIB5emQ5Uz5nlC"

server:
  port: 8081


# Database Properties
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    jdbc-url: "jdbc:postgresql://localhost:3307/vacation-manager-test"
    username: "postgres"
    password: "klopek1432"
  # Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

      # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: "update"
