/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.enterprises;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in enterprises
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>enterprises.enterprise_id_seq</code>
     */
    public static final Sequence<Integer> ENTERPRISE_ID_SEQ = Internal.createSequence("enterprise_id_seq", Enterprises.ENTERPRISES, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
