/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.enterprises;


import com.vacation.manager.jooq.enterprises.tables.Enterprise;


/**
 * Convenience access to all tables in enterprises
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>enterprises.enterprise</code>.
     */
    public static final Enterprise ENTERPRISE = Enterprise.ENTERPRISE;
}
