/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq;


import com.vacation.manager.jooq.enterprises.Enterprises;
import com.vacation.manager.jooq.leave.Leave;
import com.vacation.manager.jooq.workers.Workers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -1680380643;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>enterprises</code>.
     */
    public final Enterprises ENTERPRISES = Enterprises.ENTERPRISES;

    /**
     * The schema <code>leave</code>.
     */
    public final Leave LEAVE = Leave.LEAVE;

    /**
     * The schema <code>workers</code>.
     */
    public final Workers WORKERS = Workers.WORKERS;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.<Schema>asList(
            Enterprises.ENTERPRISES,
            Leave.LEAVE,
            Workers.WORKERS);
    }
}
