/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in company
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>company.paid_leave_id_seq</code>
     */
    public static final Sequence<Integer> PAID_LEAVE_ID_SEQ = Internal.createSequence("paid_leave_id_seq", Company.COMPANY, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>company.role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_ID_SEQ = Internal.createSequence("role_id_seq", Company.COMPANY, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>company.worker_extra_days_id_seq</code>
     */
    public static final Sequence<Integer> WORKER_EXTRA_DAYS_ID_SEQ = Internal.createSequence("worker_extra_days_id_seq", Company.COMPANY, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>company.worker_id_seq</code>
     */
    public static final Sequence<Integer> WORKER_ID_SEQ = Internal.createSequence("worker_id_seq", Company.COMPANY, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
