/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq;


import com.vacation.manager.jooq.tables.Enterprise;
import com.vacation.manager.jooq.tables.PaidLeave;
import com.vacation.manager.jooq.tables.Role;
import com.vacation.manager.jooq.tables.RoleWorker;
import com.vacation.manager.jooq.tables.Worker;
import com.vacation.manager.jooq.tables.WorkerExtraDays;


/**
 * Convenience access to all tables in company
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>company.enterprise</code>.
     */
    public static final Enterprise ENTERPRISE = Enterprise.ENTERPRISE;

    /**
     * The table <code>company.paid_leave</code>.
     */
    public static final PaidLeave PAID_LEAVE = PaidLeave.PAID_LEAVE;

    /**
     * The table <code>company.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>company.role_worker</code>.
     */
    public static final RoleWorker ROLE_WORKER = RoleWorker.ROLE_WORKER;

    /**
     * The table <code>company.worker</code>.
     */
    public static final Worker WORKER = Worker.WORKER;

    /**
     * The table <code>company.worker_extra_days</code>.
     */
    public static final WorkerExtraDays WORKER_EXTRA_DAYS = WorkerExtraDays.WORKER_EXTRA_DAYS;
}
