/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.tables.records;


import com.vacation.manager.jooq.tables.Enterprise;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnterpriseRecord extends UpdatableRecordImpl<EnterpriseRecord> implements Record4<String, Float, Boolean, LocalDate> {

    private static final long serialVersionUID = -1953468055;

    /**
     * Setter for <code>company.enterprise.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>company.enterprise.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>company.enterprise.free_days</code>.
     */
    public void setFreeDays(Float value) {
        set(1, value);
    }

    /**
     * Getter for <code>company.enterprise.free_days</code>.
     */
    public Float getFreeDays() {
        return (Float) get(1);
    }

    /**
     * Setter for <code>company.enterprise.confirmed</code>.
     */
    public void setConfirmed(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>company.enterprise.confirmed</code>.
     */
    public Boolean getConfirmed() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>company.enterprise.restart_time</code>.
     */
    public void setRestartTime(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>company.enterprise.restart_time</code>.
     */
    public LocalDate getRestartTime() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Float, Boolean, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Float, Boolean, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Enterprise.ENTERPRISE.NAME;
    }

    @Override
    public Field<Float> field2() {
        return Enterprise.ENTERPRISE.FREE_DAYS;
    }

    @Override
    public Field<Boolean> field3() {
        return Enterprise.ENTERPRISE.CONFIRMED;
    }

    @Override
    public Field<LocalDate> field4() {
        return Enterprise.ENTERPRISE.RESTART_TIME;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public Float component2() {
        return getFreeDays();
    }

    @Override
    public Boolean component3() {
        return getConfirmed();
    }

    @Override
    public LocalDate component4() {
        return getRestartTime();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public Float value2() {
        return getFreeDays();
    }

    @Override
    public Boolean value3() {
        return getConfirmed();
    }

    @Override
    public LocalDate value4() {
        return getRestartTime();
    }

    @Override
    public EnterpriseRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public EnterpriseRecord value2(Float value) {
        setFreeDays(value);
        return this;
    }

    @Override
    public EnterpriseRecord value3(Boolean value) {
        setConfirmed(value);
        return this;
    }

    @Override
    public EnterpriseRecord value4(LocalDate value) {
        setRestartTime(value);
        return this;
    }

    @Override
    public EnterpriseRecord values(String value1, Float value2, Boolean value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnterpriseRecord
     */
    public EnterpriseRecord() {
        super(Enterprise.ENTERPRISE);
    }

    /**
     * Create a detached, initialised EnterpriseRecord
     */
    public EnterpriseRecord(String name, Float freeDays, Boolean confirmed, LocalDate restartTime) {
        super(Enterprise.ENTERPRISE);

        set(0, name);
        set(1, freeDays);
        set(2, confirmed);
        set(3, restartTime);
    }
}
