/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.tables.records;


import com.vacation.manager.jooq.tables.PaidLeave;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaidLeaveRecord extends UpdatableRecordImpl<PaidLeaveRecord> implements Record7<Integer, LocalDate, Float, Integer, LocalDate, String, String> {

    private static final long serialVersionUID = 107089446;

    /**
     * Setter for <code>company.paid_leave.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>company.paid_leave.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>company.paid_leave.start_date</code>.
     */
    public void setStartDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>company.paid_leave.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>company.paid_leave.days</code>.
     */
    public void setDays(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>company.paid_leave.days</code>.
     */
    public Float getDays() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>company.paid_leave.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>company.paid_leave.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>company.paid_leave.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>company.paid_leave.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>company.paid_leave.describe</code>.
     */
    public void setDescribe(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>company.paid_leave.describe</code>.
     */
    public String getDescribe() {
        return (String) get(5);
    }

    /**
     * Setter for <code>company.paid_leave.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>company.paid_leave.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, LocalDate, Float, Integer, LocalDate, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, LocalDate, Float, Integer, LocalDate, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PaidLeave.PAID_LEAVE.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return PaidLeave.PAID_LEAVE.START_DATE;
    }

    @Override
    public Field<Float> field3() {
        return PaidLeave.PAID_LEAVE.DAYS;
    }

    @Override
    public Field<Integer> field4() {
        return PaidLeave.PAID_LEAVE.EMPLOYEE_ID;
    }

    @Override
    public Field<LocalDate> field5() {
        return PaidLeave.PAID_LEAVE.END_DATE;
    }

    @Override
    public Field<String> field6() {
        return PaidLeave.PAID_LEAVE.DESCRIBE;
    }

    @Override
    public Field<String> field7() {
        return PaidLeave.PAID_LEAVE.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getStartDate();
    }

    @Override
    public Float component3() {
        return getDays();
    }

    @Override
    public Integer component4() {
        return getEmployeeId();
    }

    @Override
    public LocalDate component5() {
        return getEndDate();
    }

    @Override
    public String component6() {
        return getDescribe();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getStartDate();
    }

    @Override
    public Float value3() {
        return getDays();
    }

    @Override
    public Integer value4() {
        return getEmployeeId();
    }

    @Override
    public LocalDate value5() {
        return getEndDate();
    }

    @Override
    public String value6() {
        return getDescribe();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public PaidLeaveRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value2(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value3(Float value) {
        setDays(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value4(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value5(LocalDate value) {
        setEndDate(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value6(String value) {
        setDescribe(value);
        return this;
    }

    @Override
    public PaidLeaveRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public PaidLeaveRecord values(Integer value1, LocalDate value2, Float value3, Integer value4, LocalDate value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaidLeaveRecord
     */
    public PaidLeaveRecord() {
        super(PaidLeave.PAID_LEAVE);
    }

    /**
     * Create a detached, initialised PaidLeaveRecord
     */
    public PaidLeaveRecord(Integer id, LocalDate startDate, Float days, Integer employeeId, LocalDate endDate, String describe, String status) {
        super(PaidLeave.PAID_LEAVE);

        set(0, id);
        set(1, startDate);
        set(2, days);
        set(3, employeeId);
        set(4, endDate);
        set(5, describe);
        set(6, status);
    }
}
