/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.tables.records;


import com.vacation.manager.jooq.tables.Worker;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerRecord extends UpdatableRecordImpl<WorkerRecord> implements Record9<Integer, String, String, Integer, String, String, String, Boolean, LocalDate> {

    private static final long serialVersionUID = -73087744;

    /**
     * Setter for <code>company.worker.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>company.worker.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>company.worker.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>company.worker.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>company.worker.enterprise_name</code>.
     */
    public void setEnterpriseName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>company.worker.enterprise_name</code>.
     */
    public String getEnterpriseName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>company.worker.employee_vars_id</code>.
     */
    public void setEmployeeVarsId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>company.worker.employee_vars_id</code>.
     */
    public Integer getEmployeeVarsId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>company.worker.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>company.worker.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>company.worker.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>company.worker.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>company.worker.occupation</code>.
     */
    public void setOccupation(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>company.worker.occupation</code>.
     */
    public String getOccupation() {
        return (String) get(6);
    }

    /**
     * Setter for <code>company.worker.confirmed</code>.
     */
    public void setConfirmed(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>company.worker.confirmed</code>.
     */
    public Boolean getConfirmed() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>company.worker.hired</code>.
     */
    public void setHired(LocalDate value) {
        set(8, value);
    }

    /**
     * Getter for <code>company.worker.hired</code>.
     */
    public LocalDate getHired() {
        return (LocalDate) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, Integer, String, String, String, Boolean, LocalDate> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, Integer, String, String, String, Boolean, LocalDate> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Worker.WORKER.ID;
    }

    @Override
    public Field<String> field2() {
        return Worker.WORKER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Worker.WORKER.ENTERPRISE_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Worker.WORKER.EMPLOYEE_VARS_ID;
    }

    @Override
    public Field<String> field5() {
        return Worker.WORKER.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return Worker.WORKER.NAME;
    }

    @Override
    public Field<String> field7() {
        return Worker.WORKER.OCCUPATION;
    }

    @Override
    public Field<Boolean> field8() {
        return Worker.WORKER.CONFIRMED;
    }

    @Override
    public Field<LocalDate> field9() {
        return Worker.WORKER.HIRED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getEnterpriseName();
    }

    @Override
    public Integer component4() {
        return getEmployeeVarsId();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getOccupation();
    }

    @Override
    public Boolean component8() {
        return getConfirmed();
    }

    @Override
    public LocalDate component9() {
        return getHired();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getEnterpriseName();
    }

    @Override
    public Integer value4() {
        return getEmployeeVarsId();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getOccupation();
    }

    @Override
    public Boolean value8() {
        return getConfirmed();
    }

    @Override
    public LocalDate value9() {
        return getHired();
    }

    @Override
    public WorkerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WorkerRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public WorkerRecord value3(String value) {
        setEnterpriseName(value);
        return this;
    }

    @Override
    public WorkerRecord value4(Integer value) {
        setEmployeeVarsId(value);
        return this;
    }

    @Override
    public WorkerRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public WorkerRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkerRecord value7(String value) {
        setOccupation(value);
        return this;
    }

    @Override
    public WorkerRecord value8(Boolean value) {
        setConfirmed(value);
        return this;
    }

    @Override
    public WorkerRecord value9(LocalDate value) {
        setHired(value);
        return this;
    }

    @Override
    public WorkerRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Boolean value8, LocalDate value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerRecord
     */
    public WorkerRecord() {
        super(Worker.WORKER);
    }

    /**
     * Create a detached, initialised WorkerRecord
     */
    public WorkerRecord(Integer id, String email, String enterpriseName, Integer employeeVarsId, String password, String name, String occupation, Boolean confirmed, LocalDate hired) {
        super(Worker.WORKER);

        set(0, id);
        set(1, email);
        set(2, enterpriseName);
        set(3, employeeVarsId);
        set(4, password);
        set(5, name);
        set(6, occupation);
        set(7, confirmed);
        set(8, hired);
    }
}
