/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.tables.records;


import com.vacation.manager.jooq.tables.WorkerExtraDays;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerExtraDaysRecord extends UpdatableRecordImpl<WorkerExtraDaysRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1010063525;

    /**
     * Setter for <code>company.worker_extra_days.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>company.worker_extra_days.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>company.worker_extra_days.seniority</code>.
     */
    public void setSeniority(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>company.worker_extra_days.seniority</code>.
     */
    public Integer getSeniority() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>company.worker_extra_days.extra_days</code>.
     */
    public void setExtraDays(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>company.worker_extra_days.extra_days</code>.
     */
    public Integer getExtraDays() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>company.worker_extra_days.annual_extra_days</code>.
     */
    public void setAnnualExtraDays(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>company.worker_extra_days.annual_extra_days</code>.
     */
    public Integer getAnnualExtraDays() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return WorkerExtraDays.WORKER_EXTRA_DAYS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return WorkerExtraDays.WORKER_EXTRA_DAYS.SENIORITY;
    }

    @Override
    public Field<Integer> field3() {
        return WorkerExtraDays.WORKER_EXTRA_DAYS.EXTRA_DAYS;
    }

    @Override
    public Field<Integer> field4() {
        return WorkerExtraDays.WORKER_EXTRA_DAYS.ANNUAL_EXTRA_DAYS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSeniority();
    }

    @Override
    public Integer component3() {
        return getExtraDays();
    }

    @Override
    public Integer component4() {
        return getAnnualExtraDays();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSeniority();
    }

    @Override
    public Integer value3() {
        return getExtraDays();
    }

    @Override
    public Integer value4() {
        return getAnnualExtraDays();
    }

    @Override
    public WorkerExtraDaysRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WorkerExtraDaysRecord value2(Integer value) {
        setSeniority(value);
        return this;
    }

    @Override
    public WorkerExtraDaysRecord value3(Integer value) {
        setExtraDays(value);
        return this;
    }

    @Override
    public WorkerExtraDaysRecord value4(Integer value) {
        setAnnualExtraDays(value);
        return this;
    }

    @Override
    public WorkerExtraDaysRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerExtraDaysRecord
     */
    public WorkerExtraDaysRecord() {
        super(WorkerExtraDays.WORKER_EXTRA_DAYS);
    }

    /**
     * Create a detached, initialised WorkerExtraDaysRecord
     */
    public WorkerExtraDaysRecord(Integer id, Integer seniority, Integer extraDays, Integer annualExtraDays) {
        super(WorkerExtraDays.WORKER_EXTRA_DAYS);

        set(0, id);
        set(1, seniority);
        set(2, extraDays);
        set(3, annualExtraDays);
    }
}
