/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.workers;


import com.vacation.manager.jooq.enterprises.tables.records.EnterpriseRecord;
import com.vacation.manager.jooq.workers.tables.Role;
import com.vacation.manager.jooq.workers.tables.RoleWorker;
import com.vacation.manager.jooq.workers.tables.Worker;
import com.vacation.manager.jooq.workers.tables.records.RoleRecord;
import com.vacation.manager.jooq.workers.tables.records.RoleWorkerRecord;
import com.vacation.manager.jooq.workers.tables.records.WorkerRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>workers</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RoleRecord, Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
    public static final Identity<WorkerRecord, Integer> IDENTITY_WORKER = Identities0.IDENTITY_WORKER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<WorkerRecord> WORKER_PKEY = UniqueKeys0.WORKER_PKEY;
    public static final UniqueKey<WorkerRecord> WORKER_USERNAME_ENTERPRISE_ID_KEY = UniqueKeys0.WORKER_USERNAME_ENTERPRISE_ID_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RoleWorkerRecord, RoleRecord> ROLE_WORKER__ROLE_WORKER_ROLE_ID_FKEY = ForeignKeys0.ROLE_WORKER__ROLE_WORKER_ROLE_ID_FKEY;
    public static final ForeignKey<WorkerRecord, EnterpriseRecord> WORKER__WORKER_ENTERPRISE_ID_FKEY = ForeignKeys0.WORKER__WORKER_ENTERPRISE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RoleRecord, Integer> IDENTITY_ROLE = Internal.createIdentity(Role.ROLE, Role.ROLE.ID);
        public static Identity<WorkerRecord, Integer> IDENTITY_WORKER = Internal.createIdentity(Worker.WORKER, Worker.WORKER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, "role_pkey", new TableField[] { Role.ROLE.ID }, true);
        public static final UniqueKey<WorkerRecord> WORKER_PKEY = Internal.createUniqueKey(Worker.WORKER, "worker_pkey", new TableField[] { Worker.WORKER.ID }, true);
        public static final UniqueKey<WorkerRecord> WORKER_USERNAME_ENTERPRISE_ID_KEY = Internal.createUniqueKey(Worker.WORKER, "worker_username_enterprise_id_key", new TableField[] { Worker.WORKER.EMAIL, Worker.WORKER.ENTERPRISE_ID }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<RoleWorkerRecord, RoleRecord> ROLE_WORKER__ROLE_WORKER_ROLE_ID_FKEY = Internal.createForeignKey(Keys.ROLE_PKEY, RoleWorker.ROLE_WORKER, "role_worker_role_id_fkey", new TableField[] { RoleWorker.ROLE_WORKER.ROLE_ID }, true);
        public static final ForeignKey<WorkerRecord, EnterpriseRecord> WORKER__WORKER_ENTERPRISE_ID_FKEY = Internal.createForeignKey(com.vacation.manager.jooq.enterprises.Keys.ENTERPRISE_PKEY, Worker.WORKER, "worker_enterprise_id_fkey", new TableField[] { Worker.WORKER.ENTERPRISE_ID }, true);
    }
}
