/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.workers;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in workers
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>workers.role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_ID_SEQ = Internal.createSequence("role_id_seq", Workers.WORKERS, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>workers.worker_id_seq</code>
     */
    public static final Sequence<Integer> WORKER_ID_SEQ = Internal.createSequence("worker_id_seq", Workers.WORKERS, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
