/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.workers;


import com.vacation.manager.jooq.workers.tables.Role;
import com.vacation.manager.jooq.workers.tables.RoleWorker;
import com.vacation.manager.jooq.workers.tables.Worker;


/**
 * Convenience access to all tables in workers
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>workers.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>workers.role_worker</code>.
     */
    public static final RoleWorker ROLE_WORKER = RoleWorker.ROLE_WORKER;

    /**
     * The table <code>workers.worker</code>.
     */
    public static final Worker WORKER = Worker.WORKER;
}
