/*
 * This file is generated by jOOQ.
 */
package com.vacation.manager.jooq.workers;


import com.vacation.manager.jooq.DefaultCatalog;
import com.vacation.manager.jooq.workers.tables.Role;
import com.vacation.manager.jooq.workers.tables.RoleWorker;
import com.vacation.manager.jooq.workers.tables.Worker;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workers extends SchemaImpl {

    private static final long serialVersionUID = -1623502604;

    /**
     * The reference instance of <code>workers</code>
     */
    public static final Workers WORKERS = new Workers();

    /**
     * The table <code>workers.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>workers.role_worker</code>.
     */
    public final RoleWorker ROLE_WORKER = RoleWorker.ROLE_WORKER;

    /**
     * The table <code>workers.worker</code>.
     */
    public final Worker WORKER = Worker.WORKER;

    /**
     * No further instances allowed
     */
    private Workers() {
        super("workers", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ROLE_ID_SEQ,
            Sequences.WORKER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Role.ROLE,
            RoleWorker.ROLE_WORKER,
            Worker.WORKER);
    }
}
